In [6]:
import numpy as np
w = np.array([1,2,3])
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
w@X.T

array([14, 32, 50])

In [4]:
w = np.array([1,2,3])
w.T


array([1, 2, 3])

In [7]:
np.zeros(2)

array([0., 0.])

In [30]:
n,d,k,sigma = 500,1000,100,1

# generate normal distributed data
X = np.random.normal(0.5, 2, (n,d)) #generate my own X (nxd) with random distribution
w_data = np.zeros(d) # given w to generate y
for j in range(k):
    w_data[j] = j/k

# standardize X
mean = np.mean(X,axis=0)
std = np.std(X,axis=0)
X_zscored = np.zeros((n,d))
for i in range(d):
    X_zscored[:,i] = (X[:,i] - mean[i])/std[i]

noise = np.random.normal(0, sigma, 500) # generate noise, bias = 0
y = X_zscored@w_data + noise # generate y = wx + noise

n,d = X_zscored.shape
w = w_data
b = (1/n)*(np.sum(y - X_zscored@w))# calculate bias
(X_zscored@w).shape


(500,)

In [29]:
y.shape

(500,)

In [20]:
c = np.zeros(d) #scalar
w = np.zeros(d) #scalar
_lambda = 0.01
a = 2*(np.linalg.norm(X, axis = 0)**2)
for k in range(d):
    WX = np.zeros(n)
    ybWX = np.zeros(n)
    for i in range(n):
        w_ = w
        w_[k] = 0 #zero at the kth entry
        WX[i] = np.dot(w_,X[i,:])
        ybWX[i] = y[i] - (b + WX[i])
    c[k] = 2* np.dot(X[:,k],ybWX) #inner product
    
    if c[k] < -_lambda:
        w[k] = (c[k] + _lambda)/a[k]
    elif c[k] > _lambda:
        w[k] = (c[k] - _lambda)/a[k]
    else:
        w[k] = 0
w.shape

(1000,)

In [24]:
n,d,k,sigma = 500,1000,100,1

# generate normal distributed data
X = np.random.normal(0.5, 2, (n,d)) #generate my own X (nxd) with random distribution
w_data = np.zeros(d) # given w to generate y
for j in range(k):
    w_data[j] = j/k

# standardize X
mean = np.mean(X,axis=0)
std = np.std(X,axis=0)
X_zscored = np.zeros((n,d))
for i in range(d):
    X_zscored[:,i] = (X[:,i] - mean[i])/std[i]

noise = np.random.normal(0, sigma, 500) # generate noise, bias = 0
y = X_zscored@w_data + noise # generate y = wx + noise

# choose the first lambda
y_mean = np.mean(y)
l = np.zeros(d)
for k in range(d):
    l[k] = 2*abs(np.dot(X[:,k],y-y_mean))
lambda_max = np.max(l)
lambda_max


2576.3321817823366