In [3]:
import numpy as np
n = 10
np.zeros([n])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
RNG = np.random.RandomState(seed=446)

# ns = [20, 200, 500, 1000]
n = 20
vanilla_times = []
numpy_times = []

# for n in ns:
    # Generate some data
x = RNG.randn(n)
y = RNG.randn(n)
A = RNG.randn(n, n)
B = RNG.randn(n, n)
# And their vanilla List equivalents
x_list = x.tolist()
y_list = y.tolist()
A_list = A.tolist()
B_list = B.tolist()

In [28]:
n = len(x_list)
f = np.zeros([n])
for j in range(n):
    row = []
    for i in range(n):
        row.append( x_list[i]*(A_list[i][j]+A_list[j][i]) + y_list[i]*B_list[i][j] )
    f[j] = np.sum(row)
f

array([-14.09850197,   9.44273109,  -0.66837814,   6.65208378,
        -0.62304648,   7.73748103, -13.71545342,   3.29476573,
        -7.51235511,   1.06708342,   2.20530248,  -9.29607287,
        -2.52131728,  -1.38120717,  -3.45971889,  -5.04679163,
       -12.30114192,  -1.736233  ,  -0.85040668,   3.20250717])

In [23]:
first = []
for i in range(n):
    first.append(x_list[i]*(A_list[i][0]+A_list[0][i]) + y_list[i]*B_list[i][0])
first

[-3.100326698850043,
 -0.8254996055980818,
 0.5535725449531226,
 -0.20058122750771745,
 -2.1398145163661226,
 -11.943040391817968,
 0.1766092761069477,
 1.9273630667383193,
 0.6465245782052136,
 4.260767640074423,
 1.3980169587289208,
 -0.32328165045530244,
 0.47224179803132105,
 -0.3568171191644949,
 0.3127025243190866,
 -1.475758280193224,
 1.546549607187989,
 -0.05930492857977854,
 -4.179273514881539,
 -0.789152027704033]

In [24]:
np.sum(first)

-14.098501966772963

In [17]:
(A.T+A)@x + B.T@y

array([-14.09850197,   9.44273109,  -0.66837814,   6.65208378,
        -0.62304648,   7.73748103, -13.71545342,   3.29476573,
        -7.51235511,   1.06708342,   2.20530248,  -9.29607287,
        -2.52131728,  -1.38120717,  -3.45971889,  -5.04679163,
       -12.30114192,  -1.736233  ,  -0.85040668,   3.20250717])